-- Fix schema to match backend code expectations

-- Update users table to match backend expectations
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'full_Name')
BEGIN
    ALTER TABLE users ADD full_Name VARCHAR(100);
    UPDATE users SET full_Name = full_name WHERE full_name IS NOT NULL;
END

-- Add missing columns to users table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'gender')
    ALTER TABLE users ADD gender VARCHAR(5);

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'DOB')
    ALTER TABLE users ADD DOB DATE;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'marital_status')
    ALTER TABLE users ADD marital_status VARCHAR(25);

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'Address')
    ALTER TABLE users ADD Address VARCHAR(50);

-- Update patients table to match backend expectations
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'patients' AND COLUMN_NAME = 'user_id')
    ALTER TABLE patients ADD user_id INT;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'patients' AND COLUMN_NAME = 'blood_group')
    ALTER TABLE patients ADD blood_group VARCHAR(5);

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'patients' AND COLUMN_NAME = 'BMI')
    ALTER TABLE patients ADD BMI VARCHAR(25);

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'patients' AND COLUMN_NAME = 'NOTES')
    ALTER TABLE patients ADD NOTES VARCHAR(50);

-- Add foreign key constraint if it doesn't exist
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_patients_users')
BEGIN
    ALTER TABLE patients ADD CONSTRAINT FK_patients_users FOREIGN KEY (user_id) REFERENCES users(user_id);
END