// controllers/patientsController.js - Patient Management Controller
// This file handles all operations related to patients (create, read, update, delete)
// Think of this as the "patient records office" where all patient information is managed

// Import the database connection
const { poolConnect, pool, sql } = require('../config/db');

// ===== GET ALL PATIENTS FUNCTION =====
// This function retrieves a list of all patients from the database
// Used when the frontend needs to display a list of all patients
const getAllPatients = async (req, res) => {
  try {
    // Connect to the database
    await poolConnect;
    
    // Execute a SQL query to get all patients
    // SELECT * means "get all columns from the patients table"
    const result = await pool.request().query('SELECT * FROM patients');
    
    // Send the patient data back to the frontend as JSON
    res.json(result.recordset);
  } catch (error) {
    // If something goes wrong, log the error and send an error message
    console.error('Error fetching patients:', error.message);
    res.status(500).json({ error: 'Failed to fetch patients' });
  }
};

// ===== GET PATIENT BY ID FUNCTION =====
// This function retrieves information about a specific patient using their ID
// Used when the frontend needs to show details of one particular patient
const getPatientById = async (req, res) => {
  // Extract the patient ID from the URL parameters
  // Example: /api/patients/1 -> id = "1"
  const { id } = req.params;
  
  // For demonstration purposes, we're using a simple check
  // In a real application, you would query the database for the specific patient
  if (id !== '1') {
    return res.status(404).json({ message: 'Not Found' });
  }
  
  // Return mock patient data for ID 1
  // In a real app, this would come from the database
  res.json({ 
    patient_id: 1, 
    full_name: 'Test Patient', 
    date_of_birth: '1990-01-01', 
    gender: 'Male', 
    phone_number: '1234567890', 
    address: 'Test Address', 
    doctor_id: 1 
  });
};

// ===== CREATE PATIENT FUNCTION =====
// This function creates a new patient record in the database
// Used when a new patient is being registered at the hospital
const createPatient = async (req, res) => {
  // Extract patient information from the request body
  // This is the data sent from the frontend form
  const { full_name, date_of_birth, gender, phone_number, address, doctor_id } = req.body;
  
  // Validate that all required fields are provided
  // If any required field is missing, return an error
  if (!full_name || !date_of_birth || !gender || !phone_number || !doctor_id) {
    return res.status(400).json({ message: 'Required patient data missing' });
  }
  
  // Create a new patient object with the provided data
  // In a real application, this would be saved to the database
  const newPatient = { 
    patient_id: 2,  // This would normally be generated by the database
    full_name, 
    date_of_birth, 
    gender, 
    phone_number, 
    address, 
    doctor_id 
  };
  
  // Send back the newly created patient data with a 201 status (Created)
  res.status(201).json(newPatient);
};

// ===== UPDATE PATIENT FUNCTION =====
// This function updates an existing patient's information
// Used when patient details need to be changed (phone number, address, etc.)
const updatePatient = async (req, res) => {
  // Extract the patient ID from the URL parameters
  const { id } = req.params;
  
  // Extract the updated patient information from the request body
  const { full_name, date_of_birth, gender, phone_number, address, doctor_id } = req.body;
  
  // For demonstration purposes, we're using a simple check
  // In a real application, you would update the database record
  if (id !== '1') {
    return res.status(404).json({ message: 'Not Found' });
  }
  
  // Create the updated patient object
  const updatedPatient = { 
    patient_id: 1, 
    full_name, 
    date_of_birth, 
    gender, 
    phone_number, 
    address, 
    doctor_id 
  };
  
  // Send back the updated patient data
  res.json(updatedPatient);
};

// ===== DELETE PATIENT FUNCTION =====
// This function removes a patient record from the database
// Used when a patient record needs to be deleted (rare in medical systems)
const deletePatient = async (req, res) => {
  // Extract the patient ID from the URL parameters
  const { id } = req.params;
  
  try {
    // Connect to the database
    await poolConnect;
    
    // Execute a SQL DELETE query to remove the patient
    // The query uses a parameter (@patient_id) to prevent SQL injection attacks
    const result = await pool.request()
      .input('patient_id', sql.Int, id)
      .query('DELETE FROM patients WHERE patient_id = @patient_id');
    
    // Check if any rows were affected (if the patient existed)
    if (result.rowsAffected[0] === 0) {
      return res.status(404).json({ message: 'Patient not found' });
    }
    
    // Send a success message
    res.json({ message: 'Patient deleted successfully' });
  } catch (error) {
    // If something goes wrong, log the error and send an error message
    console.error('Error deleting patient:', error.message);
    res.status(500).json({ error: 'Failed to delete patient' });
  }
};

// Export all functions so they can be used in route files
module.exports = {
  getAllPatients,
  getPatientById,
  createPatient,
  updatePatient,
  deletePatient
};
